# INDEX

GET http://localhost:3000/movies"

###

# CREATE

POST http://localhost/movies"
Content-Type: application/json

{
  "title": "THE TWO TOWERS",
  "year": "1998",
  "plot": "Two towers attempt to take over middle earth",
  "english": true
}